### ISSUE TITLE
Retry functionality

### ISSUE THREAD

**Issue by aprilmintacpineda** [wKovacs64/react-native-responsive-image-view#110]
Have `useResponsiveImageView` to return a call back that can be used to trigger retry load. The loading may fail for various reasons, so having retry functionality is a user-friendly thing.

**Comment by aprilmintacpineda** [comment]
I managed to get around this by doing:

```js
useResponsiveImageView({
  source: {
    uri,
    retryCount
  },
  onLoad,
  onError
});
```

`retryCount` is a dynamic variable, changing it causes the `useEffect` on the [hook](https://github.com/wKovacs64/react-native-responsive-image-view/blob/develop/useResponsiveImageView.js#L138) to be called again.

**Comment by wKovacs64** [comment]
Hey, thanks for the request! :wave:

I'm not currently working on anything in RN so this library is a bit lower on my priority list at the moment, but I'll see what I can do. PRs welcome if anyone gets to it before I can!

**Comment by aprilmintacpineda** [comment]
I'll try to send one when I can, but probably on Friday
