### ISSUE TITLE
I found several bug

### ISSUE THREAD

**Issue by showtan001** [wKovacs64/react-native-responsive-image-view#16]
The picture is too large to show,more than 1m. Can't image and text be enabled?  thanks!

**Comment by wKovacs64** [comment]
Hi @showtan001.

I'm not sure I understand the issue. Can you provide some example code reproducing the problem, possibly in a [Snack](https://snack.expo.io/)?

Thank you.

**Comment by showtan001** [comment]
@wKovacs64   
example:
 const MyTouchableComponent = ({ imageUri, onPress, contentStyle, content }) => (
    <ResponsiveImageView
        source={{ uri: imageUri }}
        render={({ getViewProps, getImageProps }) => (
            <View {...getViewProps() }>
                <TouchableHighlight onPress={onPress}>
                    <Image {...getImageProps() } />
                    <Text style={contentStyle}>{content}</Text>
                </TouchableHighlight>
            </View>
        )}
    />
);
<ScrollView style={containers}>
                {
                   ["https://s.chydof.com/yc/20180210/bb72081c659fd8f91a0c3f97f7cd3618.jpg", 
                     "https://s.chydof.com/yc/20180210/e1f905774c9558c9b1b6644f9ee2c61a.jpg", 
        "https://s.chydof.com/yc/20180210/914219e222287b92276de0b2b3867c56.jpg"].map((item, 
                     index) => (
                            <MyTouchableComponent contentStyle={{ color: '#000' }} content={index} 
                                  imageUri={item} onPress={() => { }} />
                        ))
                }
</ScrollView>
Add Text to be wrong or not to show. thanks!

**Comment by showtan001** [comment]
`const MyTouchableComponent = ({ imageUri, onPress, contentStyle, content }) => (
    <ResponsiveImageView
        source={{ uri: imageUri }}
        render={({ getViewProps, getImageProps }) => (
            <View {...getViewProps() }>
                <TouchableHighlight onPress={onPress}>
                    <Image {...getImageProps() } />
                     <Text style={contentStyle}>{content}</Text> 
                </TouchableHighlight>
            </View>
        )}
    />
);`
`let dataArr = ["https://s.chydof.com/yc/20180210/bb72081c659fd8f91a0c3f97f7cd3618.jpg", "https://s.chydof.com/yc/20180210/e1f905774c9558c9b1b6644f9ee2c61a.jpg", "https://s.chydof.com/yc/20180210/914219e222287b92276de0b2b3867c56.jpg"]
        return (
            <ScrollView style={containers}>
                {
                    dataArr.map((item, index) => {
                        return (
                            <MyTouchableComponent contentStyle={{  color: '#000' }} content={index} imageUri={item} onPress={() => { }} />
                        )
                    })
                }
            </ScrollView>
        )`
Add Text to make a mistake. Can you add Text? Thank you!

**Comment by wKovacs64** [comment]
Will this work for you?

```js
const MyTouchableComponent = ({ imageUri, onPress, contentStyle, content }) => (
  <TouchableOpacity onPress={onPress}>
    <ResponsiveImageView
      source={{ uri: imageUri }}
      render={({ getViewProps, getImageProps }) => (
        <View {...getViewProps()}>
          <Image {...getImageProps()} />
        </View>
      )}
    />
    <Text style={contentStyle}>{content}</Text>
  </TouchableOpacity>
);
```

**Comment by showtan001** [comment]
Can, thanks! Very good

**Comment by wKovacs64** [comment]
Great! Thank you.
